### ISSUE TITLE
TUI error

### ISSUE THREAD

**Issue by liushooter** [TheWaWaR/ckb-cli#7]
RUST_BACKTRACE=1

> <img width="1280" alt="1" src="https://user-images.githubusercontent.com/1235106/59558643-3f34e200-9029-11e9-8b23-b544e4542305.png">

**Comment by TheWaWaR** [comment]
Fixed in https://github.com/TheWaWaR/ckb-cli/commit/7dab5188ecd6f2530f0de78e120ee7d141ae7b01
